name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies for Module
      run: dotnet restore src/Module/Module.csproj
    
    # Optional: Ausführen der Tests
    # - name: Test
    #   run: dotnet test src/Tests/Tests.csproj --no-build --verbosity normal

    - name: Pack Module
      run: dotnet pack src/Module/Module.csproj --output ./nupkgs

    # Veröffentlichen der NuGet-Pakete
    - name: Push NuGet and Symbol Packages
      run: |
        dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        dotnet nuget push ./nupkgs/*.snupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
